name = "sink"
main = "dist/server/index.mjs"
pages_build_output_dir = "dist"
compatibility_date = "2025-11-03"
compatibility_flags = ["nodejs_compat"]
keep_vars = true
upload_source_maps = true

[ai]
binding = "AI"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "sink"

[[kv_namespaces]]
binding = "KV"
id = "a9607b4270e744aaa6ab83648f323959"
